[build-system]
requires = ["setuptools>=61.0.0"]
build-backend = "setuptools.build_meta"

[project]
name = "porgui"
version = "0.1.0"
description = "PoreGUI app and utilities"
requires-python = ">=3.9"
dependencies = [
    "image3kit",
    "streamlit",
    "streamlit_code_editor",
    "Pillow"
]

[project.optional-dependencies]
dev = ["vtk", "pyvista[jupyter]", "stpyvista", "scipy", "sqlalchemy", "imageio", "imageio-ffmpeg"]

[project.scripts]
porgui = "porgui.__main__:main"

[tool.setuptools.packages.find]
include = ["porgui*"]

[tool.pyright]
extraPaths = [
    ".",
    "porgui",
    "image3kit",
    "pnmkit",
    "snm",
    "xpm"
]

[tool.pytest.ini_options]
testpaths = ["tests"]
python_files = ["test_*.py"]

